export const SUCCESS = "SUCCESS"
export const FAIL = "FAIL"
export const LOGIN_LOADING = "LOGIN_LOADING"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const REGISTER_ERROR = "REGISTER_ERROR"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_LOADING = "REGISTER_LOADING"



